src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Annonce::class, mappedBy="user")
     */
    private $annonces;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @ORM\OneToMany(targetEntity=HistorySearch::class, mappedBy="user")
     */
    private $researchs;

    public function __construct()
    {
        $this->annonces = new ArrayCollection();
        $this->researchs = new ArrayCollection();
    }

    /**
     * @return string
     */
    public function getFullName(): string
    {
        return substr($this->getLastName(), 0, 1) . ". " . $this->getFirstName();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string)$this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string)$this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Annonce[]
     */
    public function getAnnonces(): Collection
    {
        return $this->annonces;
    }

    public function addAnnonce(Annonce $annonce): self
    {
        if (!$this->annonces->contains($annonce)) {
            $this->annonces[] = $annonce;
            $annonce->setUser($this);
        }

        return $this;
    }

    public function removeAnnonce(Annonce $annonce): self
    {
        if ($this->annonces->removeElement($annonce)) {
            // set the owning side to null (unless already changed)
            if ($annonce->getUser() === $this) {
                $annonce->setUser(null);
            }
        }

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * @return Collection|HistorySearch[]
     */
    public function getResearchs(): Collection
    {
        return $this->researchs;
    }

    public function addResearch(HistorySearch $research): self
    {
        if (!$this->researchs->contains($research)) {
            $this->researchs[] = $research;
            $research->setUser($this);
        }

        return $this;
    }

    public function removeResearch(HistorySearch $research): self
    {
        if ($this->researchs->removeElement($research)) {
            // set the owning side to null (unless already changed)
            if ($research->getUser() === $this) {
                $research->setUser(null);
            }
        }

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}Welcome!
        {% endblock %}
    </title>
    {{ encore_entry_link_tags('app') }}
    {% block stylesheets %}{% endblock %}


</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="{{ path('main') }}">DevCoin</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
            aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link mr-2" href="{{ path('annonce_new') }}">
                    <i class="fa fa-plus-square"></i>
                    Déposer une annonce
                </a>
            </li>
            <form class=" form-inline my-2 my-lg-0" action="{{ path('global_search') }}" method="post">
                <label>
                    <input class="form-control mr-sm-2" type="text" id="search" name="search" placeholder="Rechercher">
                </label>
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Rechercher</button>
            </form>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">

                <a class="nav-link" href="#">
                    <i class="fa fa-bell"></i>
                    Mes recherches
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="#">
                    <i class="fa fa-heart"></i>
                    Favoris
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="#">
                    <i class="fa fa-envelope"></i>
                    Messages
                </a>
            </li>
            {% if app.user %}
                <li class="nav-item  active dropdown">

                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" id="accountDropdownLink">
                        <img src="https://i.pravatar.cc/150?img=55" class="avatar avatar-mini" alt="Avatar de "/>
                        {{ app.user.fullName }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="accountDropdownLink">
                        <a href="{{ path('annonce_new') }}" class="dropdown-item">
                            <i class="fa fa-plus-square"></i>
                            Déposer une annonce
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="" class="dropdown-item">
                            <i class="fa fa-user-circle"></i>
                            Mon compte
                        </a>
                        <a href="{{ path('annonce_show_all') }}" class="dropdown-item">
                            <i class="fa fa-bullhorn"></i>
                            Mes annonces
                        </a>
                        <a href="{{ path('user_update', {'id': app.user.id}) }}" class="dropdown-item">
                            <i class="fa fa-user-edit"></i>
                            Modifier mon profil
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="{{ path('user_logout') }}" class="dropdown-item">
                            <i class="fa fa-sign-out-alt"></i>
                            Déconnexion
                        </a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{{ path('user_login') }}">
                        <i class="fa fa-sign-in-alt"></i>
                        Se connecter
                    </a>
                </li>
            {% endif %}

        </ul>
    </div>
</nav>
{% for label, messages in app.flashes %}
    <div class="container mt-2">
        <div class="alert alert-{{ label }}">
            {% for message in messages %}
                <p>{{ message | raw }}</p>
            {% endfor %}
        </div>
    </div>
{% endfor %}
<div class="container mt-4"> {% block body %}{% endblock %}
</div>

{{ encore_entry_script_tags('app') }}
{% block javascripts %}

{% endblock %}
</body>
</html>

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} DevCoin - Page d'accueil {% endblock %}

{% block body %}
    <h2>
        Page d'accueil
    </h2>
{% endblock %}